name = "vfdashboard"
pages_build_output_dir = "./dist"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VFDashboard"
id = "2fb3801978c44f25bde5f736f9242f7e"
